# Generated by Django 5.0.6 on 2024-07-03 16:26

import campgrounds.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('lat', models.IntegerField(null=True)),
                ('lng', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[campgrounds.models.validate_price])),
                ('location', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image_id', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campgrounds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
